"""Claim recording and LaTeX export.

Claims are flat strings (the math statement) plus an optional sortable
numeric value plus a link to the computation that produced the value.
LaTeX export renders each claim as a `\\fact{...}` macro footnoted with the
provenance ID.
"""
from __future__ import annotations

import dataclasses
import re
import secrets
from pathlib import Path
from typing import Any, Iterable

from . import assertions as _assertions
from .assertions import ClaimAssertionError, Expectation, ExpectationResult
from .serialize import hash_text
from .store import Claim, Store, get_store, utc_now_iso

LATEX_PREAMBLE = r"""% Auto-generated by claimtrail export-latex.
% Define \fact and \provid in your document preamble, e.g.:
%
%   \newcommand{\provid}[1]{\texttt{#1}}
%   \newcommand{\fact}[1]{\textbf{Claim:} #1}
%
% claimtrail footnotes each fact with its provenance computation id.
"""


def _new_claim_id() -> str:
    return secrets.token_hex(8)


PAPER_TAG = "paper"
UNBACKED_TAG = "unbacked"


class UnbackedPaperClaimError(ValueError):
    """Raised when a paper-tagged claim is registered without a computation_id.

    A claim that ships in a paper must point to a verified computation; the
    `\\provid{...}` macro in the exported LaTeX is meaningless otherwise.
    This gate exists because a paper-tagged claim with no backing computation
    silently renders as `\\provid{None}` in the exported LaTeX. Requiring the
    link makes that failure loud at claim time instead of at export time.

    Use `allow_unbacked=True` only for staged claims that you fully intend
    to back-attach via `claimtrail claim --link` before the paper is exported,
    and never for production-ready records.
    """


def claim(
    text: str,
    *,
    computation_id: str | None = None,
    value_numeric: float | int | None = None,
    notes: str | None = None,
    claim_id: str | None = None,
    deterministic_id: bool = False,
    tags: dict[str, Any] | None = None,
    allow_unbacked: bool = False,
    expect: Iterable[str | dict | Expectation] | None = None,
    force: bool = False,
) -> str:
    """Register a numerical or qualitative claim. Returns the claim id.

    By default a fresh random id is minted on every call (so the same text
    can be claimed multiple times). For idempotent batch-registration
    scripts, pass `deterministic_id=True` to derive the id from
    `(text, computation_id, value_numeric)`; re-runs with unchanged text,
    computation_id, and value_numeric then produce the same id AND the same
    row content, which is a silent no-op, not a duplicate. Or pass an
    explicit `claim_id` to control it directly.

    Re-registering an existing `claim_id` (explicit or deterministic) with
    DIFFERENT content - a different `text`, `computation_id`,
    `value_numeric`, paper tag, unbacked flag, or set of `expect`
    assertions - does NOT overwrite the stored row by default. It raises
    :class:`claimtrail.store.ClaimtrailCollisionError`, the same
    collision-safety the store applies to computations: a claim_id is
    meant to be stable, so a silent content change under an id someone may
    already be citing is exactly the failure mode this refuses. Pass
    `force=True` to replace the row anyway - the deliberate escape valve
    for a reviewed correction (see the "reviewed claim replacement"
    section of INTEGRATION.md).

    Args:
        tags: arbitrary key/value pairs stored in the `claim_tags` table.
            The key `paper` is reserved: when set, the claim is gated and
            must have a `computation_id` unless `allow_unbacked=True`.
        allow_unbacked: opt-in escape valve for staging a paper-tagged
            claim before its backing computation is available. The claim
            is still persisted; the caller must back-attach via
            `claimtrail claim --link` before LaTeX export.
        expect: structured assertions such as ``"outputs.rows == 36734685"``
            or ``"outputs.gap ~= 4.2 +- 0.05"``, checked against the linked
            computation's payload. The claim is refused with
            :class:`ClaimAssertionError` if any of them is false, and they
            are checked again by ``claimtrail check`` and ``claimtrail lint``.
        force: replace an existing row under the same `claim_id` even when
            its content differs, instead of raising
            :class:`claimtrail.store.ClaimtrailCollisionError`. Off by
            default; only pass it for a deliberate, reviewed replacement.
    """
    if not text or not isinstance(text, str):
        raise ValueError("claim text must be a non-empty string")
    norm_tags = {k: str(v) for k, v in (tags or {}).items()}
    paper = norm_tags.get(PAPER_TAG)
    if paper and computation_id is None and not allow_unbacked:
        raise UnbackedPaperClaimError(
            f"claim is tagged paper={paper!r} but has no computation_id; "
            "pass computation_id=... to link a verified computation, or "
            "allow_unbacked=True to stage the claim explicitly."
        )
    if allow_unbacked and computation_id is None:
        # Persist the intent so `claimtrail lint` can tell "opted-in unbacked"
        # apart from "forgot to attach." A later back-attach should clear
        # this flag by re-registering with the same claim_id.
        norm_tags.setdefault(UNBACKED_TAG, "true")
    expectations = [_assertions.parse_expectation(e) for e in (expect or ())]
    if expectations:
        if computation_id is None:
            raise ClaimAssertionError(
                "a claim with assertions needs a computation_id to check them against"
            )
        failed = [
            r for r in _assertions.evaluate_all(
                expectations, get_store().read_payload(computation_id)
            ) if not r.ok
        ]
        if failed:
            raise ClaimAssertionError(
                f"claim {text!r} is not supported by computation "
                f"{computation_id[:12]}: " + "; ".join(r.message for r in failed)
            )
    if claim_id is not None:
        cid = claim_id
    elif deterministic_id:
        cid = hash_text(f"{text}|{computation_id or ''}|{value_numeric if value_numeric is not None else ''}")
    else:
        cid = _new_claim_id()
    val = float(value_numeric) if value_numeric is not None else None
    rec = Claim(
        id=cid,
        text=text,
        value_numeric=val,
        computation_id=computation_id,
        created_at=utc_now_iso(),
        notes=notes,
        tags=norm_tags,
        assertions=_assertions.dumps(expectations),
    )
    get_store().insert_claim(rec, force=force)
    return cid


@dataclasses.dataclass
class ClaimCheck:
    """The result of re-checking one claim's assertions."""

    claim: Claim
    results: list[ExpectationResult]
    error: str | None = None

    @property
    def ok(self) -> bool:
        return self.error is None and all(r.ok for r in self.results)


def check_claims(store: Store | None = None, *, paper: str | None = None) -> list[ClaimCheck]:
    """Re-evaluate every claim that carries assertions.

    Pass ``paper`` to restrict the check to claims tagged with that paper
    (or report) slug. Claims without assertions are skipped: they have
    nothing a machine can check beyond their link.
    """
    store = store or get_store()
    claims = store.list_claims_by_tag(PAPER_TAG, paper) if paper else store.list_claims(limit=1_000_000)
    checks: list[ClaimCheck] = []
    for c in claims:
        expectations = _assertions.loads(c.assertions)
        if not expectations:
            continue
        if c.computation_id is None:
            checks.append(ClaimCheck(c, [], "claim has assertions but no linked computation"))
            continue
        try:
            payload = store.read_payload(c.computation_id)
        except Exception as exc:  # missing or tampered payload
            checks.append(ClaimCheck(c, [], f"payload unreadable: {exc}"))
            continue
        checks.append(ClaimCheck(c, _assertions.evaluate_all(expectations, payload)))
    return checks


_MULTIDIGIT_EXP_RE = re.compile(r"\^(\d{2,})")
_STAR_RE = re.compile(r"\s*\*\s*")
_SPACE_RE = re.compile(r" +")
_MATH_SPAN_RE = re.compile(r"\$([^$]+)\$")


def _latexify_math_span(inner: str) -> str:
    """Clean up a math-mode span. Brackets multi-digit exponents and removes
    Sage-style explicit multiplication so polynomial strings like
    `1 - X + X*q^2 - X^2*q^10` render as `1 - X + X q^{2} - X^{2} q^{10}`.

    Single-digit exponents are left alone (LaTeX renders `q^2` correctly
    without braces). The transformation is idempotent: applying it twice
    produces the same output as once.
    """
    out = _MULTIDIGIT_EXP_RE.sub(r"^{\1}", inner)
    out = _STAR_RE.sub(" ", out)
    out = _SPACE_RE.sub(" ", out).strip()
    return out


def latexify(text: str) -> str:
    """Apply LaTeX cleanup to every $...$ math span in the given text.

    Text outside math mode is left untouched. Use at render time so the
    stored claim text stays in the simple human-readable form supplied by
    the original Sage tooling.
    """
    return _MATH_SPAN_RE.sub(lambda m: f"${_latexify_math_span(m.group(1))}$", text)


def _latex_escape(s: str) -> str:
    """Minimal escape - leave $...$ math intact, escape only LaTeX-fatal chars
    that we don't expect inside math claims (%, &, #, _ outside of math).

    Math researchers write claims with embedded math like `R([\\sqrt{2}]_q) =
    0.531213`. We do not want to mangle that. We only escape characters that
    will break compilation outside of math: `%`, `&`, `#`. `_` and `^` and
    backslash are passed through (assumed to live in math mode).
    """
    out = []
    for ch in s:
        if ch == "%":
            out.append(r"\%")
        elif ch == "&":
            out.append(r"\&")
        elif ch == "#":
            out.append(r"\#")
        else:
            out.append(ch)
    return "".join(out)


def render_latex(claims: Iterable[Claim], include_preamble: bool = True) -> str:
    lines = []
    if include_preamble:
        lines.append(LATEX_PREAMBLE)
    for c in claims:
        body = latexify(_latex_escape(c.text))
        provid = c.computation_id or "no-provenance"
        lines.append(
            f"\\fact{{{body}}}\\footnote{{Provenance: \\provid{{{provid}}}"
            + (f", recorded {c.created_at}" if c.created_at else "")
            + ".}"
        )
        if c.notes:
            lines.append(f"% notes: {c.notes}")
        lines.append("")
    return "\n".join(lines)


def export_latex(
    *,
    claims_since: str | None = None,
    claims_until: str | None = None,
    output: str | Path | None = None,
    computation_id: str | None = None,
    tag_filters: dict[str, str] | None = None,
    include_unlinked: bool = True,
    include_preamble: bool = True,
) -> str:
    """Render claims to LaTeX. If `output` is given, also write to disk.

    Args:
      tag_filters: if given, restrict to claims whose linked computation
        carries every (key, value) in this dict. Used to scope an export to
        a single paper, e.g. `{"paper": "cubic-negative"}`.
      include_unlinked: when `tag_filters` is set, controls whether claims
        with no `computation_id` are still emitted. Defaults to True so a
        bare snapshot/historical claim isn't silently dropped.
    """
    store = get_store()
    rows = store.list_claims(
        since=claims_since, until=claims_until, computation_id=computation_id
    )
    if tag_filters:
        eligible_ids = {c.id for c in store.list_computations(
            limit=10_000, tag_filters=tag_filters
        )}
        filtered = []
        for c in rows:
            if c.computation_id is None:
                if include_unlinked:
                    filtered.append(c)
            elif c.computation_id in eligible_ids:
                filtered.append(c)
        rows = filtered
    text = render_latex(rows, include_preamble=include_preamble)
    if output is not None:
        Path(output).write_text(text, encoding="utf-8")
    return text
